[package]
name = "yrb"
version = "0.1.3"
authors = ["Hannes Moser <box@hannesmoser.at>", "Hannes Moser <hmoser@gitlab.com>"]
edition = "2021"
homepage = "https://github.com/y-crdt/yrb"
repository = "https://github.com/y-crdt/yrb"

[dependencies]
lib0 = "0.11.2" # must match yrs version
magnus = { git = "https://github.com/matsadler/magnus" } # waiting for release with full rb-sys backend
yrs = "0.11.2"

[dev-dependencies]
magnus = { git = "https://github.com/matsadler/magnus", features = ["embed"] } # waiting for release with full rb-sys backend


[lib]
name = "yrb"
crate-type = ["cdylib"]
